# Generated by Django 3.2 on 2022-09-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='file_extension',
            field=models.CharField(default='.invalid', max_length=30),
        ),
    ]
