# Generated by Django 3.2 on 2022-09-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_history_file_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=120)),
                ('selected_disk', models.CharField(max_length=30)),
                ('result', models.TextField(blank=True)),
                ('file_extension', models.CharField(default='invalid', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterField(
            model_name='history',
            name='file_extension',
            field=models.CharField(default='invalid', max_length=30),
        ),
    ]
